stages:
  - build
  - restart

  
jop1:
  stage: build
  script:
    - cd /home/jira-conf/jira
    - git pull origin master
    - chmod +x /home/jira-conf/jira/restart.sh
    - \cp /opt/atlassian/jira/conf/$CI_COMMIT_TITLE /opt/atlassian/jira/conf/bak/$CI_COMMIT_TITLE.`date +"%Y-%m-%d"`-`date +"%H:%M:%S"`
    - \cp /home/jira-conf/jira/$CI_COMMIT_TITLE /opt/atlassian/jira/conf/$CI_COMMIT_TITLE
  tags:
    - jira

    
jop1_sub:
  stage: restart
  script:
    - id
    - /home/jira-conf/jira/restart.sh 
  tags:
    - jira
  only:
    variables:
        - $CI_COMMIT_MESSAGE =~ /.*restart.*/
