stages:
  - PULL
  - BACKUP
  - RESTART
  
jop1:
  stage: PULL
  script:
    - cd /home/jira-conf/jira
    - git stash
    - git pull origin master
    - git stash pop
  tags:
    - jira

jop2:
  stage: BACKUP
  script:
    - chmod +x /home/jira-conf/jira/back.sh
    - /home/jira-conf/jira/back.sh
  tags:
    - jira
    
jop3:
  stage: RESTART
  script:
    - chmod +x /home/jira-conf/jira/restart.sh
    - /home/jira-conf/jira/restart.sh 
  tags:
    - jira
  only:
    variables:
        - $CI_COMMIT_MESSAGE =~ /.*restart.*/
